spring:
  application:
    name: GPT-In-Voice
  datasource:
    url: jdbc:postgresql://192.168.0.106:5433/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 768
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: nomic-embed-text:v1.5
      chat:
        model: qwen3:4b
        options:
          temperature: 0.4
          max-tokens: 16384
      init:
        pull-model-strategy: always
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
app:
  discord:
    token: ${DISCORD_TOKEN}
    guildId: ${GUILD_ID}

  speech:
    recognition:
      url: http://localhost:5000
      default-model: "whisper"
    synthesis:
      url: http://localhost:5002
      default-model: "piper"

  web:
    allowed-frontend-origin: "http://localhost:5173"

  chat:
    owner-name: "aDL1n"
    short-memory-size: 40

  rag:
    top-k: 5
    similarity-threshold: 0.8
  attention:
    mentions:
      - GPT
      - Бот
      - Валера
    mention-only: false